### ISSUE TITLE
Deprecate shenv

### ISSUE THREAD

**Issue by pawamoy** [shenv/shenv#56]
Really, this tool doesn't make sense.

What does the following even mean?

```
shenv global bash-4.4 zsh-2.3 mksh-5.1
shenv local zsh-5.0
```

These shells are all different. You're not supposed to run a script with all possible shells and all their possible versions. The `*env` tools assume there's only one primary executable that should be shim'ed. For `pyenv` it's `python`, `rbenv` `ruby`, `goenv` `go`, etc. What do we have here? `shell`. Nobody calls a script with `shell ./script`. Using shims for `sh` would be even wronger.

In fact, what would make sense is to have `bashenv`, `zshenv`, `mkshenv`, etc.

So I'll deprecate this (add a notice in the README) and archive the project.

To those who read this: feel free to fork, ask for maintainership, explain to me how/why I'm wrong, or create the right variations: `zshenv`, `mkshenv`, etc.  :slightly_smiling_face:

**Comment by scop** [comment]
The mixture doesn't seem to make sense, agreed.

However, it would be a shame if this thing would just disappear; for me it's a convenient way to manage and install a bunch of bash versions, and that in turn is useful wihen working on https://github.com/scop/bash-completion

**Comment by pawamoy** [comment]
I'm not planning to delete it, just archive it. You'd still be able to clone it and use it! Maybe you think it would be worth not to archive it though?

Maybe I'll try and create the variations for the most used shells in the near future. We could keep them here, in the `shenv` organization.

**Comment by scop** [comment]
Eventually there will be new versions of shells I'd like to use, and naturally an archived project wouldn't be updated for those.

BTW I think using `sh` shims can actually be useful in some cases, haven't used it myself but e.g. from the bash man page:
> If bash is invoked with the name sh, it tries to mimic the startup behavior of historical versions of sh as closely as possible, while conforming to the POSIX standard as well.

A `sh` shim could conceivably be used to conveniently test how something behaves when ran under that.

**Comment by scop** [comment]
Oh, and I think I can find some time to help out with something here, in addition to voicing opinions how I think things should/could be :)

**Comment by pawamoy** [comment]
> Eventually there will be new versions of shells I'd like to use, and naturally an archived project wouldn't be updated for those.

You make a point. Even if I'm not adding the new versions myself, other users might want to send PRs. Not archiving then!

About the `sh` shim, yeah it could be useful for bash, but I don't think every other shell is trying to conform to POSIX when called as `sh`.

> Oh, and I think I can find some time to help out with something here, in addition to voicing opinions how I think things should/could be :)

Great! I think it would be quite safe to add you to this organization right now, if you agree of course :slightly_smiling_face: 

By the way, I don't mind if `shenv` completely deviates from the usual `*env` working way if it means it makes more sense and works better. However I couldn't even get rid of some Python related unit tests (#2, #52) so it might be hard to do.

**Comment by scop** [comment]
> About the `sh` shim, yeah it could be useful for bash, but I don't think every other shell is trying to conform to POSIX when called as `sh`.

Sure. The bash behavior IMHO is enough reason to keep the possibility around though.

> Great! I think it would be quite safe to add you to this organization right now, if you agree of course slightly_smiling_face

Sure, feel free to add me, although I don't have anything in particular that I'd do right now.

Regarding your initial "What does the following even mean?", I think `shenv global bash-4.4 zsh-2.3 mksh-5.1 ` would mean that when one invokes `bash` with that setup active, it'll be 4.4, `zsh` gives 2.3, and `mksh` 5.1. The `sh` shim would likely point to bash-4.4. On top of that, `shenv local zsh-5.0` sets the application specific zsh, likely also `sh` while active. I'm not sure what it would do to bash or mksh, if anything.

**Comment by pawamoy** [comment]
Invitation sent!

> The sh shim would likely point to bash-4.4

Not all systems have `sh` pointing to `bash`: it would then be wrong to shim `sh` to `bash` for such systems no?

**Comment by scop** [comment]
> Invitation sent!

...aaaand accepted :)

> Not all systems have `sh` pointing to `bash`: it would then be wrong to shim `sh` to `bash` for such systems no?

Not necessarily, I see it's analoguous to (say) shimming `bash` to bash 2.x on a system whose regular bash is 5.0. It's a tool called shenv anyway, i.e. something that manages your sh. This won't change /bin/sh after all, just sh.

But then again if shenv is split to shell type specific zshenv, bashenv (w/a different name) etc projects, then messing with sh... maybe not. Dunno.

Also changing sh to something that's not bourne shell compatible at all might not be that good an idea. But again, it's just your own sh, not the system one, and perhaps you have a good reason to do it.

Just unfiltered "thinking out loud" here, haven't really thought about this before.

**Comment by pawamoy** [comment]
I'm closing this issue as the project will stay open :slightly_smiling_face: 
We can continue the discussion in a new issue if needed!
